// All copy for the close flow, in both languages.
//
// Spanish is the design language (Uruguayan register) and the domain terms are
// deliberately untranslated even in the English set: criterio, comprobante,
// e-Factura, CFE, RUT, gravado, Debe/Haber, DGI, BPS, IRAE.
//
// Re-exported through `src/lib/translations.ts` as `TRANSLATIONS[lang].close`.

export type Lang = "es" | "en";

const es = {
  shell: {
    wordmark: "Agenttis",
    clientHint: (rut: string, practice: string, criterio: string) =>
      `RUT ${rut} · ${practice} · criterio de normalización ${criterio}`,
    periodHint: "Período contable en curso",
    agentLayer: "Capa agéntica",
    agentLayerHint: "Fuentes, habilidades, agentes y observabilidad — después del MVP",
    userHint: (name: string, role: string) => `${name} · ${role}`,
    languageHint: "Cambiar idioma",
    nav: {
      resumen: "Resumen",
      datos: "Datos",
      criterio: "Criterio",
      concil: "Conciliación",
      impuestos: "Impuestos",
      entrega: "Entrega",
    },
    navHint: {
      datos: (loaded: number, expected: number) => `${loaded} de ${expected} archivos del período`,
      criterio: (avisos: number, saldos: number): string =>
        avisos + saldos > 0 ? "Hay definiciones pendientes en el criterio" : "Criterio confirmado",
      concil: (pend: number) => (pend > 0 ? `${pend} movimientos sin conciliar` : "Conciliación al día"),
      impuestos: (overdue: number) =>
        overdue > 0 ? `${overdue} obligación${overdue === 1 ? "" : "es"} vencida${overdue === 1 ? "" : "s"}` : "Sin vencimientos atrasados",
      entrega: "Libros, resumen para DGI y asientos para el ERP",
    },
    blockText: (n: number) => (n === 1 ? "1 definición pendiente" : `${n} definiciones pendientes`),
    allResolved: "Todo resuelto",
    closePeriod: (label: string) => `Cerrar ${label.toLowerCase()}`,
    closed: (label: string) => `${label} cerrado`,
    reopen: "Reabrir período",
    footerLeft: "© 2026 Agenttis Inc.",
    footerRight: (criterio: string, practice: string) => `Criterio de normalización ${criterio} · ${practice}`,
  },

  resumen: {
    title: (label: string) => `Cierre de ${label.toLowerCase()}`,
    subtitle: "Solo lo que necesita tu decisión. El resto ya está resuelto.",
    closedNote: (label: string) => `${label} quedó cerrado. Podés reabrirlo si aparece algo más.`,
    ventas: "Ventas",
    compras: "Compras",
    ivaAPagar: (due: string) => `IVA a pagar · vence ${due}`,
    ventasHint: (n: number, g22: string, g10: string, ex: string) =>
      `${n} comprobantes emitidos · ${g22} gravado 22%, ${g10} gravado 10%, ${ex} exento`,
    comprasHint: (n: number, g22: string, g10: string, ex: string) =>
      `${n} comprobantes recibidos · ${g22} gravado 22%, ${g10} gravado 10%, ${ex} exento`,
    ivaHint: (ventas: string, compras: string) => `IVA ventas ${ventas} menos crédito de compras ${compras}`,
    queueTitle: (n: number) =>
      n === 0 ? "Listo para cerrar" : n === 1 ? "Falta 1 definición para cerrar" : `Faltan ${n} definiciones para cerrar`,
    doneToggle: (n: number, open: boolean) =>
      `${open ? "Ocultar los " : ""}${n} paso${n === 1 ? "" : "s"} que ya se resolvieron solos`,
  },

  steps: {
    importar: {
      label: "Importar archivos del período",
      detail: (loaded: number, expected: number, missing: string) =>
        missing ? `${loaded} archivos leídos · falta ${missing}` : `${loaded} de ${expected} archivos leídos`,
      right: (loaded: number, expected: number) => `${loaded} de ${expected}`,
      action: "Subir",
    },
    normalizar: {
      label: "Normalizar al criterio del estudio",
      detail: (n: number, file: string, problems: string) =>
        `${n} filas con avisos en ${file}: ${problems}`,
      right: (n: number) => `${n} aviso${n === 1 ? "" : "s"}`,
      action: "Revisar",
    },
    saldos: {
      label: "Confirmar saldos iniciales",
      detail: (n: number, names: string) =>
        `${n} cuenta${n === 1 ? "" : "s"} sin equivalencia en el plan del estudio: ${names}`,
      action: "Definir",
    },
    emitidos: {
      label: "Verificar comprobantes emitidos",
      detail: (n: number) => `${n} e-facturas, todas dentro del período`,
    },
    recibidos: {
      label: "Verificar comprobantes recibidos",
      detail: (n: number) => `${n} comprobantes registrados`,
    },
    concil: {
      label: "Conciliación bancaria",
      detail: (n: number) =>
        n > 0 ? `${n} movimientos del banco sin respaldo en los libros` : "Todos los movimientos tienen respaldo",
      action: "Conciliar",
    },
    iva: {
      label: "Calcular IVA del período (22% / 10%)",
      detail: (amount: string, due: string) => `IVA a pagar ${amount}, vence el ${due}`,
    },
    nomina: {
      label: "Liquidar aportes de nómina",
      detail: (days: number) => `Aportes BPS de mayo vencidos hace ${days} días`,
      detailDone: "Aportes BPS al día",
      action: "Regularizar",
    },
    entrega: {
      label: "Entregar el paquete de cierre",
      detail: "Libros, resumen para DGI y asientos para el ERP",
      detailDone: (when: string) => `Paquete generado ${when}`,
      action: "Preparar",
    },
  },

  datos: {
    title: "Datos del período",
    subtitle: "Subí los archivos como los tengas. Pasá el cursor sobre cada uno para ver el detalle.",
    dropTitle: "Arrastrá tus archivos acá",
    dropHint: "CSV, XLSX o TXT · se detecta el tipo por su contenido",
    dropBusy: "Leyendo el archivo…",
    kind: { compras: "Compras", ventas: "Ventas", saldos: "Saldos iniciales", extracto: "Extracto bancario", desconocido: "Sin clasificar" },
    fileHint: (kind: string, rows: number, when: string) => `${kind} · ${rows} filas · cargado ${when}`,
    saldosHint: (lines: number, total: string) => `Saldos iniciales · ${lines} líneas · Debe = Haber $ ${total}`,
    extractoHint: (bank: string, rows: number) => `${bank} · ${rows} movimientos`,
    statusNormalizado: "Normalizado",
    statusAvisos: (n: number) => `${n} fila${n === 1 ? "" : "s"} requiere${n === 1 ? "" : "n"} atención`,
    statusCuentas: (n: number) => `${n} cuenta${n === 1 ? "" : "s"} sin definir`,
    statusSinCargar: "Sin cargar",
    statusServidor: "Se lee en el servidor",
    servidorHint: "XLSX se procesa del lado del servidor — disponible con la capa agéntica",
    statusSinClasificar: "No reconocimos el tipo",
    sinClasificarHint: "Ninguna columna coincide con compras, ventas, saldos ni extracto",
    verCriterio: "Ver criterio",
    revisar: "Revisar",
    definir: "Definir",
    subir: "Subir",
    quitar: "Quitar",
    justNow: "recién",
  },

  criterio: {
    back: "Datos del período",
    subtitle: (rows: number, ok: number, avisos: number) =>
      `${rows} filas · ${ok} listas · ${avisos} con aviso`,
    subtitleClean: (rows: number) => `${rows} filas · todas listas`,
    columnsHint: (recognised: number, unused: string[]) =>
      `${recognised} columnas reconocidas${unused.length ? ` · ${unused.length} sin usar: ${unused.join(", ")}` : ""}`,
    mapTitle: "Correspondencia de columnas",
    mapHint: (sample: string, conf: string) => `Ejemplo en el archivo: ${sample} · certeza ${conf}`,
    exceptionsTitle: (n: number) => `${n} fila${n === 1 ? "" : "s"} requiere${n === 1 ? "" : "n"} atención`,
    exceptionsClear: "Sin filas con aviso",
    resolveAll: "Resolver una por una",
    resolveStop: "Dejar para después",
    resolveProgress: (i: number, n: number) => `Aviso ${i} de ${n}`,
    apply: (fix: string) => fix,
    skip: "Dejar como está",
    previewToggle: (open: boolean): string => (open ? "Ocultar cómo queda la fila 1" : "Ver cómo queda la fila 1"),
    preview: { fecha: "Fecha", tipo: "Tipo CFE", rut: "RUT emisor", g22: "Gravado 22%", iva: "IVA 22%", total: "Total" },
    remember: (owner: string) => `Recordar este criterio para ${owner}`,
    cancel: "Cancelar",
    confirm: (n: number) => `Confirmar ${n} filas`,
    confirmed: "Criterio confirmado",
  },

  saldos: {
    back: "Datos del período",
    title: (date: string) => `Saldos iniciales al ${date}`,
    subtitle: (ok: number, total: number) =>
      ok === total
        ? `Las ${total} líneas quedaron interpretadas.`
        : `${ok} de ${total} líneas se interpretaron sin ambigüedad. Definí ${total - ok === 1 ? "la restante" : `las ${total - ok} restantes`}.`,
    balanced: (total: string) => `Debe = Haber · ${total}`,
    unbalanced: (diff: string) => `Debe y Haber difieren en ${diff}`,
    balancedHint: "El archivo cierra: la suma del debe iguala la del haber",
    unbalancedHint: "El archivo no cierra — revisá el origen antes de confirmar",
    thText: "Texto en el archivo",
    thCuenta: "Cuenta del plan",
    thDebe: "Debe",
    thHaber: "Haber",
    sinDefinir: "Sin definir",
    lineHint: "No hay una cuenta equivalente en el plan del estudio",
    showing: (shown: number, total: number) => `Mostrando ${shown} de ${total} líneas`,
    showAll: "Ver todas",
    showLess: "Ver menos",
    decisionsTitle: (n: number) => `${n} cuenta${n === 1 ? "" : "s"} necesita${n === 1 ? "" : "n"} tu decisión`,
    decisionHint: (amount: string, side: string) => `$ ${amount} al ${side}`,
    choose: "Elegí una cuenta…",
    confirm: "Confirmar saldos iniciales",
    allSet: "Saldos iniciales confirmados",
  },

  concil: {
    title: "Conciliación bancaria",
    subtitle: "Elegí un movimiento y confirmá con qué comprobante corresponde.",
    subtitleHint: (bank: string, bankBal: string, booksBal: string) =>
      `${bank} · saldo banco ${bankBal} · saldo libros ${booksBal}`,
    aExplicar: "A explicar",
    diffHint: "Diferencia entre el saldo del banco y el de los libros",
    movimientos: "Movimientos",
    filters: { all: "Todos", pend: "Pendientes", ok: "Conciliados" },
    rowHint: (date: string, ref: string, settled: boolean) =>
      `${date} · ${ref} · ${settled ? "conciliado" : "pendiente de conciliar"}`,
    footer: (visible: number, total: number, diff: string) =>
      `${visible} de ${total} movimientos · diferencia ${diff}`,
    selHint: (date: string, ref: string, amount: string) => `${date} · ${ref} · ${amount}`,
    candTitle: "Coincidencias propuestas, con su motivo",
    settledTitle: "Conciliado con",
    noCandidates: "No encontramos un comprobante que corresponda.",
    conciliar: "Conciliar",
    descartar: "Descartar",
    conciliado: "Conciliado",
    deshacer: "Deshacer",
    buscarOtro: "Buscar otro comprobante…",
    buscarPlaceholder: "Número, cliente o importe",
    sinComprobante: "Registrar sin comprobante",
    sinComprobanteDoc: "Registrado sin comprobante",
    sinComprobanteWhy: "Queda asentado contra una cuenta puente, a la espera del respaldo.",
    searchWhy: (amount: string) => `Elegido a mano · importe del comprobante ${amount}`,
    empty: "No hay movimientos con este filtro.",
  },

  impuestos: {
    title: "Obligaciones del período",
    subtitle: "Calculadas sobre los libros normalizados.",
    vence: (d: string) => `vence ${d}`,
    presentado: "presentado",
    regularizar: "Regularizar",
    regularizado: "regularizado",
    vencidoHint: (detail: string, days: number) => `${detail} · vencía hace ${days} días`,
    pendienteHint: (detail: string, due: string) => `${detail} · vence el ${due}`,
    ivaHint: (ventas: string, compras: string) => `IVA ventas ${ventas} menos crédito de compras ${compras}`,
    booksToggle: (open: boolean): string => (open ? "Ocultar los libros del período" : "Ver de dónde salen estos importes"),
    thLibro: "Libro",
    thG22: "Gravado 22",
    thG10: "Gravado 10",
    thExento: "Exento",
    thIva: "IVA",
    thTotal: "Total",
    ventas: "Ventas",
    compras: "Compras",
    ivaAPagar: "IVA a pagar",
    ivaAFavor: "IVA a favor",
  },

  entrega: {
    title: "Entrega del cierre",
    subtitle:
      "Un paquete de planillas con el formato que espera cada destino. El formato queda recordado para este cliente.",
    queIncluye: "Qué incluye",
    selected: (n: number, total: number) => `${n} de ${total} seleccionados`,
    deliverables: {
      compras: { label: "Libro de compras", meta: (n: number) => `${n} filas`, hint: "Un renglón por comprobante recibido, con IVA discriminado por tasa" },
      ventas: { label: "Libro de ventas", meta: (n: number) => `${n} filas`, hint: "Un renglón por comprobante emitido, con IVA discriminado por tasa" },
      iva: { label: "Resumen de IVA del período", meta: () => "1 hoja", hint: "Los totales que van a la declaración mensual, con el detalle que los origina" },
      asientos: { label: "Asientos de ajuste para el ERP", meta: (n: number) => `${n} asientos`, hint: "Asientos de cierre listos para importar en el sistema del cliente" },
      apertura: { label: "Balance de apertura confirmado", meta: (n: number) => `${n} cuentas`, hint: "Los saldos iniciales ya mapeados al plan del estudio" },
      concil: { label: "Conciliación bancaria", meta: (n: number) => `${n} movimientos`, hint: "Movimientos del banco con el comprobante que los respalda; los pendientes quedan marcados" },
    },
    formatLabel: "Formato de columnas",
    formats: {
      dgi: "Resumen para DGI",
      memory: "ERP — Memory",
      zureo: "ERP — Zureo",
      plano: "CSV plano · una fila por comprobante",
    },
    formatHints: {
      dgi: "Columnas y totales agrupados como los pide el formulario mensual: gravado 22, gravado 10, exento, IVA e IVA compras.",
      memory: "Layout de importación de Memory: fecha, cuenta, debe, haber, concepto y número de comprobante.",
      zureo: "Layout de importación de Zureo, con código de cuenta y centro de costo en columnas separadas.",
      plano: "Una fila por comprobante con todos los campos del criterio del estudio, sin agrupar.",
    },
    structureLabel: "Estructura del archivo",
    one: "Un libro por hoja",
    many: "Un archivo por libro",
    warn: (n: number) => `Quedan ${n} definiciones pendientes: el paquete sale marcado como provisorio.`,
    generate: "Generar paquete de cierre",
    generateEmpty: "Elegí al menos una planilla",
    lastDelivery: (when: string) => `Última entrega: ${when}`,
    lastDeliveryHint: (fmt: string, sheets: number) => `${fmt} · ${sheets} hojas`,
    generated: (n: number) => `Paquete generado · ${n} archivo${n === 1 ? "" : "s"} descargado${n === 1 ? "" : "s"}`,
  },
};

const en: typeof es = {
  shell: {
    wordmark: "Agenttis",
    clientHint: (rut, practice, criterio) => `RUT ${rut} · ${practice} · normalisation criterio ${criterio}`,
    periodHint: "Accounting period in progress",
    agentLayer: "Agentic layer",
    agentLayerHint: "Sources, skills, agents and observability — after the MVP",
    userHint: (name, role) => `${name} · ${role}`,
    languageHint: "Change language",
    nav: { resumen: "Overview", datos: "Data", criterio: "Criterio", concil: "Reconciliation", impuestos: "Taxes", entrega: "Delivery" },
    navHint: {
      datos: (loaded, expected) => `${loaded} of ${expected} files for the period`,
      criterio: (avisos, saldos) => (avisos + saldos > 0 ? "The criterio still needs decisions" : "Criterio confirmed"),
      concil: (pend) => (pend > 0 ? `${pend} unreconciled movements` : "Reconciliation up to date"),
      impuestos: (overdue) => (overdue > 0 ? `${overdue} overdue obligation${overdue === 1 ? "" : "s"}` : "Nothing overdue"),
      entrega: "Books, DGI summary and ERP journal entries",
    },
    blockText: (n) => (n === 1 ? "1 decision pending" : `${n} decisions pending`),
    allResolved: "All resolved",
    closePeriod: (label) => `Close ${label.toLowerCase()}`,
    closed: (label) => `${label} closed`,
    reopen: "Reopen period",
    footerLeft: "© 2026 Agenttis Inc.",
    footerRight: (criterio, practice) => `Normalisation criterio ${criterio} · ${practice}`,
  },

  resumen: {
    title: (label) => `${label} close`,
    subtitle: "Only what needs your decision. The rest is already resolved.",
    closedNote: (label) => `${label} is closed. Reopen it if something else turns up.`,
    ventas: "Sales",
    compras: "Purchases",
    ivaAPagar: (due) => `VAT payable · due ${due}`,
    ventasHint: (n, g22, g10, ex) => `${n} documents issued · ${g22} taxed 22%, ${g10} taxed 10%, ${ex} exempt`,
    comprasHint: (n, g22, g10, ex) => `${n} documents received · ${g22} taxed 22%, ${g10} taxed 10%, ${ex} exempt`,
    ivaHint: (ventas, compras) => `Sales VAT ${ventas} less purchase credit ${compras}`,
    queueTitle: (n) => (n === 0 ? "Ready to close" : n === 1 ? "1 decision left to close" : `${n} decisions left to close`),
    doneToggle: (n, open) => `${open ? "Hide the " : ""}${n} step${n === 1 ? "" : "s"} that resolved themselves`,
  },

  steps: {
    importar: {
      label: "Import the period's files",
      detail: (loaded, expected, missing) => (missing ? `${loaded} files read · missing ${missing}` : `${loaded} of ${expected} files read`),
      right: (loaded, expected) => `${loaded} of ${expected}`,
      action: "Upload",
    },
    normalizar: {
      label: "Normalise to the practice's criterio",
      detail: (n, file, problems) => `${n} rows flagged in ${file}: ${problems}`,
      right: (n) => `${n} flag${n === 1 ? "" : "s"}`,
      action: "Review",
    },
    saldos: {
      label: "Confirm opening balances",
      detail: (n, names) => `${n} account${n === 1 ? "" : "s"} with no equivalent in the practice's chart: ${names}`,
      action: "Define",
    },
    emitidos: { label: "Verify issued documents", detail: (n) => `${n} e-Facturas, all within the period` },
    recibidos: { label: "Verify received documents", detail: (n) => `${n} documents registered` },
    concil: {
      label: "Bank reconciliation",
      detail: (n) => (n > 0 ? `${n} bank movements with no backing in the books` : "Every movement is backed"),
      action: "Reconcile",
    },
    iva: { label: "Compute the period's VAT (22% / 10%)", detail: (amount, due) => `VAT payable ${amount}, due ${due}` },
    nomina: {
      label: "Settle payroll contributions",
      detail: (days) => `May BPS contributions overdue by ${days} days`,
      detailDone: "BPS contributions up to date",
      action: "Settle",
    },
    entrega: {
      label: "Deliver the closing package",
      detail: "Books, DGI summary and ERP journal entries",
      detailDone: (when) => `Package generated ${when}`,
      action: "Prepare",
    },
  },

  datos: {
    title: "Files for the period",
    subtitle: "Upload the files however you have them. Hover any one for the detail.",
    dropTitle: "Drop your files here",
    dropHint: "CSV, XLSX or TXT · the type is detected from the contents",
    dropBusy: "Reading the file…",
    kind: { compras: "Purchases", ventas: "Sales", saldos: "Opening balances", extracto: "Bank statement", desconocido: "Unclassified" },
    fileHint: (kind, rows, when) => `${kind} · ${rows} rows · loaded ${when}`,
    saldosHint: (lines, total) => `Opening balances · ${lines} lines · Debe = Haber $ ${total}`,
    extractoHint: (bank, rows) => `${bank} · ${rows} movements`,
    statusNormalizado: "Normalised",
    statusAvisos: (n) => `${n} row${n === 1 ? "" : "s"} need${n === 1 ? "s" : ""} attention`,
    statusCuentas: (n) => `${n} account${n === 1 ? "" : "s"} undefined`,
    statusSinCargar: "Not uploaded",
    statusServidor: "Read on the server",
    servidorHint: "XLSX is parsed server-side — available with the agentic layer",
    statusSinClasificar: "Type not recognised",
    sinClasificarHint: "No column matches purchases, sales, balances or a bank statement",
    verCriterio: "View criterio",
    revisar: "Review",
    definir: "Define",
    subir: "Upload",
    quitar: "Remove",
    justNow: "just now",
  },

  criterio: {
    back: "Files for the period",
    subtitle: (rows, ok, avisos) => `${rows} rows · ${ok} ready · ${avisos} flagged`,
    subtitleClean: (rows) => `${rows} rows · all ready`,
    columnsHint: (recognised, unused) =>
      `${recognised} columns recognised${unused.length ? ` · ${unused.length} unused: ${unused.join(", ")}` : ""}`,
    mapTitle: "Column mapping",
    mapHint: (sample, conf) => `Sample in the file: ${sample} · certainty ${conf}`,
    exceptionsTitle: (n) => `${n} row${n === 1 ? "" : "s"} need${n === 1 ? "s" : ""} attention`,
    exceptionsClear: "No flagged rows",
    resolveAll: "Resolve one by one",
    resolveStop: "Leave for later",
    resolveProgress: (i, n) => `Flag ${i} of ${n}`,
    apply: (fix) => fix,
    skip: "Leave as is",
    previewToggle: (open) => (open ? "Hide how row 1 ends up" : "See how row 1 ends up"),
    preview: { fecha: "Date", tipo: "CFE type", rut: "Issuer RUT", g22: "Taxed 22%", iva: "VAT 22%", total: "Total" },
    remember: (owner) => `Remember this criterio for ${owner}`,
    cancel: "Cancel",
    confirm: (n) => `Confirm ${n} rows`,
    confirmed: "Criterio confirmed",
  },

  saldos: {
    back: "Files for the period",
    title: (date) => `Opening balances at ${date}`,
    subtitle: (ok, total) =>
      ok === total
        ? `All ${total} lines are mapped.`
        : `${ok} of ${total} lines were read unambiguously. Define the remaining ${total - ok}.`,
    balanced: (total) => `Debe = Haber · ${total}`,
    unbalanced: (diff) => `Debe and Haber differ by ${diff}`,
    balancedHint: "The file balances: debits equal credits",
    unbalancedHint: "The file does not balance — check the source before confirming",
    thText: "Text in the file",
    thCuenta: "Chart account",
    thDebe: "Debe",
    thHaber: "Haber",
    sinDefinir: "Undefined",
    lineHint: "No equivalent account in the practice's chart",
    showing: (shown, total) => `Showing ${shown} of ${total} lines`,
    showAll: "Show all",
    showLess: "Show fewer",
    decisionsTitle: (n) => `${n} account${n === 1 ? "" : "s"} need${n === 1 ? "s" : ""} your decision`,
    decisionHint: (amount, side) => `$ ${amount} on the ${side}`,
    choose: "Pick an account…",
    confirm: "Confirm opening balances",
    allSet: "Opening balances confirmed",
  },

  concil: {
    title: "Bank reconciliation",
    subtitle: "Pick a movement and confirm which document it corresponds to.",
    subtitleHint: (bank, bankBal, booksBal) => `${bank} · bank balance ${bankBal} · books balance ${booksBal}`,
    aExplicar: "To explain",
    diffHint: "Difference between the bank balance and the books",
    movimientos: "Movements",
    filters: { all: "All", pend: "Pending", ok: "Reconciled" },
    rowHint: (date, ref, settled) => `${date} · ${ref} · ${settled ? "reconciled" : "pending"}`,
    footer: (visible, total, diff) => `${visible} of ${total} movements · difference ${diff}`,
    selHint: (date, ref, amount) => `${date} · ${ref} · ${amount}`,
    candTitle: "Proposed matches, with the reason",
    settledTitle: "Reconciled with",
    noCandidates: "We found no document that corresponds.",
    conciliar: "Reconcile",
    descartar: "Discard",
    conciliado: "Reconciled",
    deshacer: "Undo",
    buscarOtro: "Search another document…",
    buscarPlaceholder: "Number, client or amount",
    sinComprobante: "Record without a document",
    sinComprobanteDoc: "Recorded without a document",
    sinComprobanteWhy: "Booked against a suspense account until the backing arrives.",
    searchWhy: (amount) => `Chosen by hand · document amount ${amount}`,
    empty: "No movements under this filter.",
  },

  impuestos: {
    title: "Obligations for the period",
    subtitle: "Computed on the normalised books.",
    vence: (d) => `due ${d}`,
    presentado: "filed",
    regularizar: "Settle",
    regularizado: "settled",
    vencidoHint: (detail, days) => `${detail} · was due ${days} days ago`,
    pendienteHint: (detail, due) => `${detail} · due ${due}`,
    ivaHint: (ventas, compras) => `Sales VAT ${ventas} less purchase credit ${compras}`,
    booksToggle: (open) => (open ? "Hide the period's books" : "See where these amounts come from"),
    thLibro: "Book",
    thG22: "Taxed 22",
    thG10: "Taxed 10",
    thExento: "Exempt",
    thIva: "VAT",
    thTotal: "Total",
    ventas: "Sales",
    compras: "Purchases",
    ivaAPagar: "VAT payable",
    ivaAFavor: "VAT credit",
  },

  entrega: {
    title: "Closing delivery",
    subtitle: "A package of sheets in the format each destination expects. The format is remembered for this client.",
    queIncluye: "What it includes",
    selected: (n, total) => `${n} of ${total} selected`,
    deliverables: {
      compras: { label: "Purchase book", meta: (n) => `${n} rows`, hint: "One line per document received, VAT split by rate" },
      ventas: { label: "Sales book", meta: (n) => `${n} rows`, hint: "One line per document issued, VAT split by rate" },
      iva: { label: "VAT summary for the period", meta: () => "1 sheet", hint: "The totals that go on the monthly return, with the detail behind them" },
      asientos: { label: "Adjustment entries for the ERP", meta: (n) => `${n} entries`, hint: "Closing entries ready to import into the client's system" },
      apertura: { label: "Confirmed opening balance", meta: (n) => `${n} accounts`, hint: "Opening balances already mapped to the practice's chart" },
      concil: { label: "Bank reconciliation", meta: (n) => `${n} movements`, hint: "Bank movements with the document backing them; pending ones stay flagged" },
    },
    formatLabel: "Column format",
    formats: { dgi: "DGI summary", memory: "ERP — Memory", zureo: "ERP — Zureo", plano: "Flat CSV · one row per document" },
    formatHints: {
      dgi: "Columns and totals grouped the way the monthly form asks for them: taxed 22, taxed 10, exempt, VAT and purchase VAT.",
      memory: "Memory's import layout: date, account, debit, credit, description and document number.",
      zureo: "Zureo's import layout, with account code and cost centre in separate columns.",
      plano: "One row per document with every field of the practice's criterio, ungrouped.",
    },
    structureLabel: "File structure",
    one: "One book per sheet",
    many: "One file per book",
    warn: (n) => `${n} decisions are still pending: the package goes out marked provisional.`,
    generate: "Generate closing package",
    generateEmpty: "Pick at least one sheet",
    lastDelivery: (when) => `Last delivery: ${when}`,
    lastDeliveryHint: (fmt, sheets) => `${fmt} · ${sheets} sheets`,
    generated: (n) => `Package generated · ${n} file${n === 1 ? "" : "s"} downloaded`,
  },
};

export type CloseCopy = typeof es;

export const CLOSE_COPY: Record<Lang, CloseCopy> = { es, en };
